init;
load_system('algorithm');

disp('1. Adding annotations and descriptions to submodules...');

%% 1. Feedforward Decoupling
ff_sub = 'algorithm/current_control/Feedforward Decoupling';
ff_text = sprintf([...
'FIELD-ORIENTED CONTROL: FEEDFORWARD VOLTAGE DECOUPLING\n', ...
'======================================================\n', ...
'1. WHAT IT DOES:\n', ...
'Computes and injects speed-dependent cross-coupling and rotor back-EMF feedforward\n', ...
'voltages (Vd_ff, Vq_ff) directly into the d- and q-axis voltage commands.\n\n', ...
'2. GOVERNING MOTOR EQUATIONS (Synchronous Rotor dq-Frame):\n', ...
'  v_d = R_s * i_d + L_d * (di_d/dt) - omega_e * L_q * i_q\n', ...
'  v_q = R_s * i_q + L_q * (di_q/dt) + omega_e * L_d * i_d + omega_e * lambda_pm\n\n', ...
'where:\n', ...
'  omega_e   = P * omega_m         [Electrical angular speed, rad/s]\n', ...
'  P         = 4                   [Pole pairs]\n', ...
'  L_d, L_q  = 0.35 mH, 0.55 mH    [Direct and quadrature axis inductances]\n', ...
'  lambda_pm = 0.0604 Wb           [Permanent magnet flux linkage]\n\n', ...
'3. FEEDFORWARD DECOUPLING FORMULAS:\n', ...
'  Vd_ff = - omega_e * L_q * i_q\n', ...
'  Vq_ff = + omega_e * (L_d * i_d + lambda_pm)\n\n', ...
'Voltage commands to inverter:\n', ...
'  v_d* = v_d_PI + Vd_ff\n', ...
'  v_q* = v_q_PI + Vq_ff\n\n', ...
'4. WHY IT IS NEEDED:\n', ...
'- Nonlinear Decoupling: In IPMSMs, d and q dynamics are strongly coupled through\n', ...
'  rotor velocity. Without feedforward, i_q transients disturb i_d and vice versa.\n', ...
'- High-Speed Back-EMF & Cross-Coupling Rejection: At maximum speed (20,000 RPM),\n', ...
'  omega_e reaches ~8,377 rad/s, producing back-EMF > 500 V and cross-coupling > 200 V.\n', ...
'  Without feedforward, the feedback PI integrators must synthesize these huge voltages\n', ...
'  purely through tracking error, resulting in severe phase lag, overshoot, and windup.\n', ...
'- Ideal Linear SISO Plant: Feedforward cancels the coupling voltages, reducing the\n', ...
'  plant seen by the PI controllers to two independent linear first-order SISO loops:\n', ...
'    v_d_PI ≈ R_s * i_d + L_d * (di_d/dt)\n', ...
'    v_q_PI ≈ R_s * i_q + L_q * (di_q/dt)\n', ...
'  ensuring uniform 800 Hz current loop bandwidth across the entire speed envelope.']);

set_param(ff_sub, 'Description', ff_text);
a = find_system(ff_sub, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'annotation');
delete(a);
annot_ff = Simulink.Annotation([ff_sub '/Doc']);
annot_ff.Text = ff_text;
annot_ff.Position = [50, 310];
annot_ff.DropShadow = 'on';
annot_ff.Interpreter = 'off';
annot_ff.FontSize = 10;
annot_ff.FontName = 'Arial';

%% 2. FW Demag Floor
fw_sub = 'algorithm/current_control/FW Demag Floor';
fw_text = sprintf([...
'FIELD WEAKENING DEMAGNETIZATION FLOOR (PHYSICAL VOLTAGE ENVELOPE)\n', ...
'=================================================================\n', ...
'1. WHAT IT DOES:\n', ...
'Computes the maximum permissible stator flux linkage for the current rotor speed\n', ...
'given the inverter voltage headroom, calculates the minimum negative d-axis\n', ...
'demagnetization current required to stay within that flux limit, and enforces this\n', ...
'floor on id_ref.\n\n', ...
'2. MATHEMATICAL FORMULAS:\n', ...
'  omega_e      = P * |omega_m|\n', ...
'  omega_e_safe = max(omega_e, 100 rad/s)          [Zero-speed division guard]\n', ...
'  V_max        = V_phase_max = 0.92 * V_dc / sqrt(3) ≈ 318.7 V\n\n', ...
'Maximum allowable stator flux linkage before voltage saturation:\n', ...
'  lambda_max   = V_max / omega_e_safe\n\n', ...
'Required d-axis current to suppress stator flux to lambda_max:\n', ...
'  i_d_floor_raw = (lambda_max - lambda_pm) / L_d\n', ...
'  i_d_floor     = min(0, i_d_floor_raw)           [No positive FW magnetizing current]\n\n', ...
'Effective d-axis current reference output:\n', ...
'  id_ref_out   = min(id_ref_in, i_d_floor)        [Enforces minimum negative d-axis floor]\n\n', ...
'3. WHY IT IS NEEDED:\n', ...
'- Open-Circuit Back-EMF Overvoltage: Above base speed (N_base ≈ 9,500 RPM), the rotor\n', ...
'  PM flux generates a back-EMF (omega_e * lambda_pm) exceeding available phase voltage.\n', ...
'  At 18,000-20,000 RPM, back-EMF exceeds 450-500 V against a 318.7 V inverter limit.\n', ...
'- Inverter Saturation Prevention: If the speed/MTPA loop cannot request negative i_d\n', ...
'  fast enough during rapid acceleration, the inverter saturates, current regulation\n', ...
'  collapses, and catastrophic uncontrolled braking/regeneration occurs.\n', ...
'- Deterministic Safety Floor: FW Demag Floor acts as an instantaneous, feedforward\n', ...
'  physical constraint that guarantees stator terminal back-EMF remains feasible at all RPM.']);

set_param(fw_sub, 'Description', fw_text);
a = find_system(fw_sub, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'annotation');
delete(a);
annot_fw = Simulink.Annotation([fw_sub '/Doc']);
annot_fw.Text = fw_text;
annot_fw.Position = [50, 220];
annot_fw.DropShadow = 'on';
annot_fw.Interpreter = 'off';
annot_fw.FontSize = 10;
annot_fw.FontName = 'Arial';

%% 3. adc_to_sensor
adc_sub = 'algorithm/adc_to_sensor';
adc_text = sprintf([...
'EVADC TO PHYSICAL SENSOR MEASUREMENT CONDITIONING\n', ...
'=================================================\n', ...
'1. WHAT IT DOES:\n', ...
'Hardware abstraction interface that transforms raw 12-bit integer counts from the\n', ...
'Infineon AURIX TC387 EVADC into single-precision physical SI measurements packed into\n', ...
'the ''algo_measurement'' bus.\n\n', ...
'2. INTERFACE SIGNALS:\n', ...
'- Input:  ''adc_values'' bus (uint16 channels: ia, ib, ic, resolver_sin, resolver_cos)\n', ...
'- Output: ''measurements'' bus (algo_measurement):\n', ...
'    * currents [A]    : 3-phase stator currents (Phase A, B, C)\n', ...
'    * MtrPos   [rad]  : Mechanical rotor angle in [0, 2*pi)\n', ...
'    * speed    [rad/s]: Filtered mechanical rotor speed\n\n', ...
'3. INTERNAL SUBMODULES:\n', ...
'  1) Current measurement: Signed offset removal & scaling (0..4095 counts -> -120..+120 A).\n', ...
'  2) Position measurement: Center removal, normalization, atan2, and [0, 2*pi) wrapping.\n', ...
'  3) Speed from position: Differentiator with circular 2*pi unwrapping & 150 Hz LPF.\n\n', ...
'4. WHY IT IS NEEDED:\n', ...
'Decouples microcontroller register hardware formats from core FOC algorithms, ensuring\n', ...
'pure single-precision floating-point execution, determinism, and seamless code generation.\n', ...
'Execution rate: Ts = 50 us (20 kHz).']);

set_param(adc_sub, 'Description', adc_text);
a = find_system(adc_sub, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'annotation');
delete(a);
annot_adc = Simulink.Annotation([adc_sub '/Doc']);
annot_adc.Text = adc_text;
annot_adc.Position = [40, 390];
annot_adc.DropShadow = 'on';
annot_adc.Interpreter = 'off';
annot_adc.FontSize = 10;
annot_adc.FontName = 'Arial';

%% 4. Current measurement (inside adc_to_sensor)
cur_sub = 'algorithm/adc_to_sensor/Current measurement';
cur_text = sprintf([...
'STATOR PHASE CURRENT MEASUREMENT & SCALING\n', ...
'==========================================\n', ...
'1. WHAT IT DOES:\n', ...
'Converts 12-bit unsigned ADC counts (0..4095) from current sensors into signed\n', ...
'phase currents in Amperes for phases A, B, and C.\n\n', ...
'2. CONVERSION FORMULA:\n', ...
'For each phase k in {a, b, c}:\n', ...
'  i_k = (ADC_k - ADC_mid) * (I_max / ADC_span)\n', ...
'      = (single(ADC_k) - 2048.0) * (120.0 / 2047.0)  [Amperes]\n\n', ...
'Calibration parameters (sensor struct):\n', ...
'  ADC_mid  = 2048   [Zero-current center code, 2.5 V mid-rail]\n', ...
'  ADC_span = 2047   [Unipolar count span]\n', ...
'  I_max    = 120.0  [Transducer full-scale current, A]\n\n', ...
'3. WHY IT IS NEEDED:\n', ...
'Hall-effect current sensors produce an analog voltage centered at 2.5 V (count 2048)\n', ...
'for 0 A, swinging between 0 V (count 0, ≈ -120 A) and 5 V (count 4095, +120 A).\n', ...
'This block converts discrete integer ADC codes to physical currents for Clarke transformation.']);

set_param(cur_sub, 'Description', cur_text);
a = find_system(cur_sub, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'annotation');
delete(a);
annot_cur = Simulink.Annotation([cur_sub '/Doc']);
annot_cur.Text = cur_text;
annot_cur.Position = [700, 100];
annot_cur.DropShadow = 'on';
annot_cur.Interpreter = 'off';
annot_cur.FontSize = 10;
annot_cur.FontName = 'Arial';

%% 5. Position measurement (inside adc_to_sensor)
pos_sub = 'algorithm/adc_to_sensor/Position measurement';
pos_text = sprintf([...
'RESOLVER ROTOR POSITION DECODING & CIRCULAR WRAPPING\n', ...
'===================================================\n', ...
'1. WHAT IT DOES:\n', ...
'Demodulates and converts orthogonal resolver envelope ADC counts into mechanical rotor\n', ...
'position angle in radians, strictly wrapped to the single-turn interval [0, 2*pi).\n\n', ...
'2. MATHEMATICAL FORMULAS:\n', ...
'  sin_norm = (single(adc_sin) - 2048.0) / 2047.0\n', ...
'  cos_norm = (single(adc_cos) - 2048.0) / 2047.0\n', ...
'  theta_raw = atan2(sin_norm, cos_norm)           [Range: (-pi, +pi] rad]\n', ...
'  position_rad = mod(theta_raw, 2*pi)             [Range: [0, 2*pi) rad]\n\n', ...
'3. WHY IT IS NEEDED:\n', ...
'Field-Oriented Control requires accurate, continuous knowledge of rotor position to align\n', ...
'the Park and Clarke reference frames. Using atan2(sin, cos) provides amplitude-invariant\n', ...
'angle reconstruction that rejects common-mode excitation variations and noise. Wrapping to\n', ...
'[0, 2*pi) provides a clean, standardized mechanical coordinate system for electrical angle derivation.']);

set_param(pos_sub, 'Description', pos_text);
a = find_system(pos_sub, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'annotation');
delete(a);
annot_pos = Simulink.Annotation([pos_sub '/Doc']);
annot_pos.Text = pos_text;
annot_pos.Position = [65, 430];
annot_pos.DropShadow = 'on';
annot_pos.Interpreter = 'off';
annot_pos.FontSize = 10;
annot_pos.FontName = 'Arial';

%% 6. Speed from position (inside adc_to_sensor)
spd_sub = 'algorithm/adc_to_sensor/Speed from position';
spd_text = sprintf([...
'SPEED ESTIMATION: CIRCULAR UNWRAPPING & LOW-PASS FILTERING\n', ...
'==========================================================\n', ...
'1. WHAT IT DOES:\n', ...
'Calculates mechanical angular velocity (speed_rad_s) from rotor position samples,\n', ...
'unwrapping circular 2*pi phase boundaries, suppressing startup spikes, and filtering\n', ...
'quantization noise.\n\n', ...
'2. MATHEMATICAL FORMULAS:\n', ...
'Sample-to-sample angular difference:\n', ...
'  delta_theta = position_rad(k) - position_rad(k-1)\n\n', ...
'Circular shortest-path unwrapping (handles 0 <-> 2*pi transitions):\n', ...
'  delta_theta_unwrap = delta_theta - 2*pi * round(delta_theta / (2*pi))\n\n', ...
'Differentiated raw speed (with first-step startup suppression):\n', ...
'  omega_raw(1) = 0\n', ...
'  omega_raw(k) = delta_theta_unwrap / Ts          [Ts = 50 us (20 kHz)]\n\n', ...
'Discrete 1st-order Low-Pass Filter (cutoff fc = 150 Hz):\n', ...
'  omega_filt(k) = (1 - alpha) * omega_filt(k-1) + alpha * omega_raw(k)\n', ...
'  alpha = (2*pi * fc * Ts) / (1 + 2*pi * fc * Ts) ≈ 0.04505\n\n', ...
'3. WHY IT IS NEEDED:\n', ...
'- Boundary Wrap Immunity: As the rotor rotates past 2*pi -> 0 or 0 -> 2*pi, delta_theta\n', ...
'  would jump by +/-2*pi, producing an enormous false velocity spike (+/-125,663 rad/s).\n', ...
'  Shortest-path unwrapping eliminates this completely.\n', ...
'- Startup Quiescence: Suppressing the first step prevents false speed kicks when starting\n', ...
'  from a nonzero stationary angle.\n', ...
'- Noise Rejection: Differentiating quantized 12-bit ADC resolver signals amplifies high-\n', ...
'  frequency quantization noise; the 150 Hz LPF smooths the velocity signal for stable speed\n', ...
'  and current loop feedback.']);

set_param(spd_sub, 'Description', spd_text);
a = find_system(spd_sub, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'annotation');
delete(a);
annot_spd = Simulink.Annotation([spd_sub '/Doc']);
annot_spd.Text = spd_text;
annot_spd.Position = [80, 500];
annot_spd.DropShadow = 'on';
annot_spd.Interpreter = 'off';
annot_spd.FontSize = 10;
annot_spd.FontName = 'Arial';

disp('2. Rearranging top-level blocks in algorithm...');
% Set positions
set_param('algorithm/setpoints',              'Position', [40,  310,  70,  330]);
set_param('algorithm/rpm2rads',                'Position', [140, 305, 190, 335]);
set_param('algorithm/speed_control',            'Position', [260, 285, 400, 365]);
set_param('algorithm/MTPA Control Reference',   'Position', [480, 295, 610, 375]);
set_param('algorithm/current_control',          'Position', [700, 295, 830, 445]);
set_param('algorithm/duty_cycles',              'Position', [910, 360, 940, 380]);

set_param('algorithm/adc_values',               'Position', [40,  485,  70,  505]);
set_param('algorithm/adc_to_sensor',            'Position', [140, 455, 270, 535]);
set_param('algorithm/bus_selector_meas',        'Position', [350, 475, 355, 515]);

set_param('algorithm/rads2rpm',                 'Position', [310, 195, 360, 225]);
set_param('algorithm/Speed',                    'Position', [420, 160, 455, 230]);
set_param('algorithm/IdIq',                     'Position', [670, 160, 705, 230]);

disp('3. Re-routing ONLY top-level lines cleanly...');
lines_top = find_system('algorithm', 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'line');
delete(lines_top);

l1 = add_line('algorithm', 'setpoints/1', 'rpm2rads/1', 'autorouting', 'smart');
l2 = add_line('algorithm', 'setpoints/1', 'Speed/1', 'autorouting', 'smart');
set_param(l1, 'Name', 'spd_ref_rpm');

l3 = add_line('algorithm', 'rpm2rads/1', 'speed_control/1', 'autorouting', 'smart');
set_param(l3, 'Name', 'spd_ref_rads');

l4 = add_line('algorithm', 'speed_control/1', 'MTPA Control Reference/1', 'autorouting', 'smart');
set_param(l4, 'Name', 'torque_ref');

l5 = add_line('algorithm', 'MTPA Control Reference/1', 'current_control/1', 'autorouting', 'smart');
l6 = add_line('algorithm', 'MTPA Control Reference/1', 'IdIq/1', 'autorouting', 'smart');
set_param(l5, 'Name', 'id_ref');

l7 = add_line('algorithm', 'MTPA Control Reference/2', 'current_control/2', 'autorouting', 'smart');
l8 = add_line('algorithm', 'MTPA Control Reference/2', 'IdIq/2', 'autorouting', 'smart');
set_param(l7, 'Name', 'iq_ref');

l9 = add_line('algorithm', 'current_control/1', 'duty_cycles/1', 'autorouting', 'smart');
set_param(l9, 'Name', 'duty_cycles');

l10 = add_line('algorithm', 'adc_values/1', 'adc_to_sensor/1', 'autorouting', 'smart');
l11 = add_line('algorithm', 'adc_to_sensor/1', 'bus_selector_meas/1', 'autorouting', 'smart');
l12 = add_line('algorithm', 'adc_to_sensor/1', 'current_control/3', 'autorouting', 'smart');

l13 = add_line('algorithm', 'bus_selector_meas/1', 'speed_control/2', 'autorouting', 'smart');
l14 = add_line('algorithm', 'bus_selector_meas/1', 'MTPA Control Reference/2', 'autorouting', 'smart');
l15 = add_line('algorithm', 'bus_selector_meas/1', 'rads2rpm/1', 'autorouting', 'smart');

l16 = add_line('algorithm', 'rads2rpm/1', 'Speed/2', 'autorouting', 'smart');
set_param(l16, 'Name', 'meas_speed_rpm');

save_system('algorithm');
if ~exist('images', 'dir'), mkdir('images'); end
print('-salgorithm', '-dpng', 'images/algorithm_layout.png');
print('-salgorithm/current_control/Feedforward Decoupling', '-dpng', 'images/ff_decoupling.png');
print('-salgorithm/current_control/FW Demag Floor', '-dpng', 'images/fw_demag_floor.png');
print('-salgorithm/adc_to_sensor', '-dpng', 'images/adc_to_sensor.png');
print('-salgorithm/adc_to_sensor/Current measurement', '-dpng', 'images/adc_current_meas.png');
print('-salgorithm/adc_to_sensor/Position measurement', '-dpng', 'images/adc_position_meas.png');
print('-salgorithm/adc_to_sensor/Speed from position', '-dpng', 'images/adc_speed_meas.png');

disp('4. Running validation suite...');
results = validate_adc_to_sensor;
disp(results);
disp('>>> ALL VALIDATION PASSED SUCCESSFULLY! <<<');
