%% run_angle_calibration.m
% Commission the physical resolver zero using the TC387 target.
% Deliberately requires an explicit arm variable because this enables all six
% gate drivers and applies the stationary alignment vector.

if ~exist('confirmHardwareCalibration', 'var') || ...
        ~isequal(confirmHardwareCalibration, true)
    error(['Calibration is armed only when confirmHardwareCalibration=true. ' ...
        'Verify DC bus limits, motor restraint, resolver wiring and emergency stop first.']);
end

if ~exist('calibrationDcBusVoltage', 'var'), calibrationDcBusVoltage = 20.0; end
if ~exist('calibrationCurrentTarget', 'var'), calibrationCurrentTarget = 0.4; end
motorPhaseResistance = 0.126;
calibrationModulation = calibrationCurrentTarget * motorPhaseResistance / calibrationDcBusVoltage;
assert(calibrationDcBusVoltage > 0 && calibrationDcBusVoltage <= 30, ...
    'Commissioning DC bus must be in the protected low-voltage range (0..30 V).');
assert(calibrationCurrentTarget > 0 && calibrationCurrentTarget <= 0.5, ...
    'Commissioning current target must be in the protected low-current range (0..0.5 A).');
assert(calibrationModulation <= 0.005, 'Calculated calibration modulation is unexpectedly high.');
fprintf('Bench calibration: Vdc=%.2f V, target=%.3f A, modulation=%.6f\n', ...
    calibrationDcBusVoltage, calibrationCurrentTarget, calibrationModulation);

simulinkDir = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(simulinkDir, 'scripts'));
try
    wait_for_xcp('192.168.0.10', 5555, '192.168.0.100', 3);
catch
    warning('XCP is unavailable; proceeding through the active winIDEA debugger connection.');
end

winideaPython = 'C:\winIDEA\Python\python.exe';
if ~exist(winideaPython, 'file'), winideaPython = 'python'; end
helper = fullfile(tempdir, 'stugverter_calibrate_resolver.py');
code = sprintf([ ...
    'import isystem.connect as ic, time, sys\n', ...
    'cm=ic.ConnectionMgr(); cm.connectMRU("")\n', ...
    'dbg=ic.CDebugFacade(cm)\n', ...
    'def read(name): return dbg.evaluate(ic.IConnectDebug.fMonitor,name)\n', ...
    'def write(name,value): dbg.modify(ic.IConnectDebug.fMonitor,name,str(value))\n', ...
    'write("g_hil_mode_enable",0); write("control_enable_request",0); write("control_mode_request",0)\n', ...
    'write("calibration_modulation","%.9g")\n', ...
    'time.sleep(0.1)\n', ...
    'if read("g_gate_drivers_enabled").getInt()!=0: raise RuntimeError("gate enables did not return low before arming")\n', ...
    'write("control_mode_request",1); write("control_enable_request",1)\n', ...
    'deadline=time.time()+3.0; seen_gate=False; seen_clear=False\n', ...
    'try:\n', ...
    '  while time.time()<deadline:\n', ...
    '    gates=read("g_gate_drivers_enabled").getInt(); settle=read("g_calibration_settle_count").getInt(); samples=read("g_calibration_sample_count").getInt(); done=read("g_calibration_complete").getInt()\n', ...
    '    du=read("g_duty_u").getFloat(); dv=read("g_duty_v").getFloat(); dw=read("g_duty_w").getFloat()\n', ...
    '    ia=(read("g_adc_raw_curr_u").getInt()-2048)*0.05; ib=(read("g_adc_raw_curr_v").getInt()-2048)*0.05; iw=(read("g_adc_raw_curr_w").getInt()-2048)*0.05\n', ...
    '    rs=read("g_adc_raw_res_sin").getInt()-2048; rc=read("g_adc_raw_res_cos").getInt()-2048\n', ...
    '    import math; angle=math.atan2(rs,rc)\n', ...
    '    seen_gate = seen_gate or gates==1; seen_clear = seen_clear or done==0\n', ...
    '    print(f"CAL gates={gates} duty=[{du:.5f},{dv:.5f},{dw:.5f}] Iabc=[{ia:.2f},{ib:.2f},{iw:.2f}]A angle={angle:.5f}rad settle={settle}/5000 samples={samples}/10000 done={done}")\n', ...
    '    if done and seen_gate and seen_clear:\n', ...
    '      time.sleep(0.05); offset=read("resolver_angle_offset").getFloat(); gates=read("g_gate_drivers_enabled").getInt(); enabled=read("control_enable_request").getInt()\n', ...
    '      if gates!=0 or enabled!=0: raise RuntimeError("unsafe calibration completion state")\n', ...
    '      print(f"CALIBRATION_OK offset_rad={offset:.7f} gates={gates} enable={enabled}"); sys.exit(0)\n', ...
    '    time.sleep(0.05)\n', ...
    '  raise RuntimeError("calibration timeout")\n', ...
    'finally:\n', ...
    '  write("control_enable_request",0); write("control_mode_request",0)\n'], ...
    calibrationModulation);
fid = fopen(helper, 'w'); assert(fid ~= -1, 'Cannot create calibration helper.');
fwrite(fid, code); fclose(fid);
cleanup = onCleanup(@() deleteIfPresent(helper));
[status, output] = system(sprintf('"%s" "%s"', winideaPython, helper));
fprintf('%s\n', output);
assert(status == 0 && contains(output, 'CALIBRATION_OK'), ...
    'Physical resolver calibration failed; control was returned to OFF.');

function deleteIfPresent(path)
if exist(path, 'file'), delete(path); end
end
